# всегда добавлять точку с запятой (;) в конце каждой инструкции
semi: true

# Все строки будут форматироваться с использованием одинарных кавычек (') вместо двойных (").
singleQuote: true

# Ширина табуляции
tabWidth: 4

# Максимальная длина строки
printWidth: 100

# добавлять завершающие запятые
trailingComma: es5

# два пробела перед  правилом в .scss
overrides:
    - files: '*.scss'
      options:
          tabWidth: 2
